export const LIST_ISLOADING = "LIST_ISLOADING" 
export const LIST_FETCHSUCCESS = "LIST_FETCHSUCCESS"
export const LIST_SELECTRESTAURANT = "LIST_SELECTRESTAURANT"

export const ORDER_ISLOADING = "ORDER_ISLOADING"
export const ORDER_POSTSUCCESS = "ORDER_POSTSUCCESS"
export const ORDER_ETA = "ORDER_ETA"